### PR TITLE
Fix error with raw JSON data

### PR DESCRIPTION
**Pull request by steffendsommer**
Ran into a simple issue where it would only validate with form data, but not with raw JSON data. Please let me know if I might have used it wrongly.

### CODE REVIEW

**Comment by bygri** [comment]
I _think_ I was expecting JSON to be converted into Node first, but if it's simple enough to handle JSON as it stands, then this is a great addition. Could you please add a test `testValidateFromJSON()` underneath `testValidateFromContentObject()` including this use case?

Feel free to update the README too, if you'd like, as it's currently the only source of documentation.

**Comment by steffendsommer** [comment]
Looking at the tests I realized that it's probably better to solve this in `Request+Content.swift`, as we can just unwrap the json data using `.node`. I'm closing this and making another PR.

**Comment by steffendsommer** [comment]
It took me a while figuring out why my test would succeed without adding this addition to the package. The reason was that I was not requiring any fields, which basically skips validation if fields are not parsed correctly - this can easily lead to false positives. I've added requirement for fields both for the existing test `testValidateFromContentObject()` and my added `testValidateFromJSON ()`.

I did not update the readme as this was expected to work when parsing the data using `request.data` as I see it - let me know if you agree.

**Comment by bygri** [comment]
Excellent - thank you very much.

**Pull request merged**
